server:
  port: 9000

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
        endpoint:
          token-introspection-uri: /oauth2/token-info
  application:
    name: auth-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      password: redis_pass

eureka:
  client:
    enabled: false
jwt:
  secret: ${JWT_SECRET}
  access_expiration: ${JWT_EXPIRATION}
  refresh_expiration: ${JWT_EXPIRATION}

logging:
  level:
    org.springframework.security: trace