spring:
  config:
    import: optional:configserver:http://loclahost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/agroswit
    username: user
    password: pass

jwt:
  secret: 6E5A7234753778214125442A472D4A614E645267556B58703273357638792F42
  access_expiration: 15
  refresh_expiration: 30

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka