spring:
  config:
    import: optional:configserver:http://config-server:8888
    activate:
      on-profile: docker
---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  application:
    name: catalog-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cache:
    redis:
      time-to-live: 300000
      cache-null-values: false

logging:
  level:
    org.springframework.security: trace