spring:
  config:
    import: optional:configserver:http://config-server:8888
    activate:
      on-profile: docker
---
spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cache:
    redis:
      time-to-live: 300000
      cache-null-values: false