spring:
  config:
    import: optional:file:./env.properties
  application:
    name: agroswit
  flyway:
    enabled: false
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 500KB
      max-request-size: 500KB
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
file-storage:
  upload-dir: ${FILE_UPLOAD_DIR}