version: '3'
services:
  db:
    image: mysql:8.3
    ports:
      - "30306:3306"
    environment:
      MYSQL_DATABASE: agroswit
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: