version: "3.9"

services:
  config-server:
    container_name: config-server
    image: glumaks/agroswit-config-server
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8888/management || exit 1
      interval: 10s
      timeout: 2s
      retries: 5
    env_file:
      - .env.prod
    networks:
      - cloud-network

  discovery-server:
    container_name: discovery-server
    image: glumaks/agroswit-discovery-server
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:7777/eureka/apps || exit 1
      interval: 10s
      timeout: 2s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - "7777:7777"
    networks:
      - cloud-network

  gateway-server:
    container_name: gateway-server
    image: glumaks/agroswit-gateway-server
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8080/management || exit 1
      interval: 10s
      timeout: 2s
      retries: 5
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - cloud-network

  catalog-service:
    container_name: catalog-service
    image: glumaks/agroswit-catalog-service
    restart: unless-stopped
    environment:
      - DB_URL=${PRODUCT_SERVICE_DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MINIO_URL=http://${HOST_IP}:9000
      - MINIO_BUCKET=${PRODUCT_SERVICE_MINIO_BUCKET}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    depends_on:
      gateway-server:
        condition: service_healthy
    networks:
      - cloud-network

  inventory-service:
    container_name: inventory-service
    image: glumaks/agroswit-inventory-service
    restart: unless-stopped
    environment:
      - DB_URL=${INVENTORY_SERVICE_DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      gateway-server:
        condition: service_healthy
    networks:
      - cloud-network

  minio:
    image: minio/minio:RELEASE.2024-04-06T05-26-02Z.fips
    restart: unless-stopped
    ports:
      - '9090:9090'
      - '9000:9000'
    command: server ~/minio --console-address :9090
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    networks:
      - cloud-network
    volumes:
      - minio_data:/data

networks:
  cloud-network:
    driver: bridge

volumes:
  minio_data:
    driver: local
  cache:
    driver: local