version: "3.9"

services:
  config-server:
    container_name: config-server
    build:
      context: ./config-server
    healthcheck:
      test: curl --fail http://localhost:8888/management || exit 1
      interval: 5s
      timeout: 2s
      retries: 5
    env_file:
      - .env
    networks:
      - cloud-network

  discovery-server:
    container_name: discovery-server
    build:
      context: ./discovery-server
    healthcheck:
      test: curl --fail http://localhost:7777/eureka/apps || exit 1
      interval: 5s
      timeout: 2s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - cloud-network

  gateway-server:
    container_name: gateway-server
    build:
      context: ./api-gateway
    healthcheck:
      test: curl --fail http://localhost:8080/management || exit 1
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - cloud-network

  product-service:
    container_name: product-service
    build:
      context: ./product-service
    environment:
      - SPRING_DATASOURCE_URL=${PRODUCT_SERVICE_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${PRODUCT_SERVICE_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PRODUCT_SERVICE_DB_PASSWORD}
      - MINIO_BUCKET=${PRODUCT_SERVICE_MINIO_BUCKET}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    depends_on:
      gateway-server:
        condition: service_healthy
    networks:
      - cloud-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  inventory-service:
    container_name: inventory-service
    environment:
      - SPRING_R2DBC_URL=${INVENTORY_SERVICE_DB_URL}
      - SPRING_R2DBC_USERNAME=${INVENTORY_SERVICE_DB_USERNAME}
      - SPRING_R2DBC_PASSWORD=${INVENTORY_SERVICE_DB_PASSWORD}
    build:
      context: ./inventory-service
    depends_on:
      gateway-server:
        condition: service_healthy
    networks:
      - cloud-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  minio:
    image: minio/minio:latest
    ports:
      - '9090:9090'
      - '9000:9000'
    command: server ~/minio --console-address :9090
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    networks:
      - cloud-network
    volumes:
      - minio_data

networks:
  cloud-network:
    driver: bridge
volumes:
  minio_data: