server:
  port: 9000

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  access_expiration: ${JWT_EXPIRATION}
  refresh_expiration: ${JWT_EXPIRATION}
