spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agroswit
    username: user
    password: pass
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      password: redis_pass
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
        endpoint:
          token-introspection-uri: /oauth2/token-info
logging:
  level:
    org.springframework.security: trace

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:7777/eureka

jwt:
  access_expiration: 15
  refresh_expiration: 30
  secret: 6E5A7234753778214125442A472D4A614E645267556B58703273357638792F42
