server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agroswit
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    problemdetails:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka