server:
  port: 8083

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 500KB
      max-request-size: 500KB
  data:
    web:
      pageable:
        one-indexed-parameters: true
  mvc:
    problemdetails:
      enabled: true

minio:
  bucket: ${MINIO_BUCKET}
  endpoint: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}