spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agroswit
    username: user
    password: pass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka

minio:
  bucket: images
  endpoint: http://localhost:9000
  access-key: minio_user
  secret-key: minio_pass