spring:
  config:
    import: file:./env.properties
  application:
    name: agroswit
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 500KB
      max-request-size: 500KB
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
file-storage:
  upload-dir: ${FILE_UPLOAD_DIR}