spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
jwt:
  secret:
    key: 073b794f75cea3b0a3b2a8a9804e52e98a302a54febb365a9603024e1fa5925a
    expiration: 300000
