spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: misha
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret:
    key: 073b794f75cea3b0a3b2a8a9804e52e98a302a54febb365a9603024e1fa5925a
    expiration: 300000
