create table category
(
    id                 integer generated by default as identity,
    parent_category_id integer,
    name               varchar(30) not null unique,
    description        varchar(300),
    primary key (id),
    constraint category_name_parent_cat_id_uk unique (name, parent_category_id)
);

create table category_property
(
    category_id integer      not null,
    id          integer generated by default as identity,
    type        varchar(10)  not null check (type in ('TEXT', 'NUMBER')),
    name        varchar(255) not null,
    primary key (id),
    constraint cat_prop_name_cat_id_uk unique (name, category_id)
);

create table producer
(
    id       integer generated by default as identity,
    logo_url varchar(255) not null unique,
    name     varchar(255) not null unique,
    primary key (id)
);

create table product
(
    id            integer generated by default as identity,
    image_url     varchar(255),
    name          varchar(30) not null unique,
    description   varchar(500),
    category_id   integer,
    producer_id   integer,
    article_1c_id integer unique,
    primary key (id)
);

create table package
(
    id integer generated by default as identity ,
    price      float(53)    not null,
    product_id integer      not null,
    volume     integer      not null,
    unit       varchar(255) not null check (unit in ('BAG', 'BIG_BAG', 'KG', 'L')),
    primary key (id)
);

create table product_property_value
(
    product_id  integer      not null,
    property_id integer      not null,
    prop_value  varchar(255) not null,
    primary key (product_id, property_id)
);

create table users
(
    id       integer generated by default as identity,
    login    varchar(20)  not null unique,
    name     varchar(30),
    surname  varchar(30),
    password varchar(200) not null,
    role     varchar(255) check (role in ('USER', 'ADMIN')),
    primary key (id)
);

create table order_state
(
    name varchar(30) not null,
    primary key (name)
);

create table orders
(
    id         integer generated by default as identity,
    state      varchar(30) not null,
    created_at timestamp,
    user_id    integer     not null,
    primary key (id)
);

create table order_items
(
    id         integer generated by default as identity,
    order_id   integer not null,
    product_id integer not null,
    package_id integer not null,
    count      integer not null
);

create table order_history
(
    order_id    integer     not null,
    state       varchar(30) not null,
    modified_at timestamp,
    user_id     integer     not null,
    primary key (order_id)
);

alter table orders
    add constraint orders_state_fk
        foreign key (state) references order_state;

alter table orders
    add constraint orders_user_id_fk
        foreign key (user_id) references users;

alter table order_items
    add constraint order_item_ordr_id_fk
        foreign key (order_id) references orders;
alter table order_items
    add constraint order_item_prod_id_fk
        foreign key (product_id) references product;
alter table order_items
    add constraint order_item_pckg_id_fk
        foreign key (package_id) references package;

alter table order_history
    add constraint order_history_state_fk
        foreign key (state) references order_state;

alter table order_history
    add constraint orders_history_user_id_fk
        foreign key (user_id) references users;

alter table if exists category
    add constraint category_prnt_cat_id
        foreign key (parent_category_id) references category;

alter table if exists category_property
    add constraint category_property_cat_id_fk
        foreign key (category_id) references category;

alter table if exists product
    add constraint FK1mtsbur82frn64de7balymq9s
        foreign key (category_id)
            references category;
alter table if exists product
    add constraint FKaxeo9fj1sfah36yd9bujs8qft
        foreign key (producer_id)
            references producer;