spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/agroswit
    username: user
    password: pass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka