spring:
  config:
    import: optional:configserver:http://config-server:8888
    activate:
      on-profile: docker
---
spring:
  application:
    name: inventory-service
  config:
    import: "optional:configserver:http://localhost:8888"