server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: product-service-detailed
#          uri: lb://product-service
#          predicates:
#            - Method=GET
#            - Path=/api/v1/products/**
#          filters:
##            - RewritePath=/api/v1/products, /api/v1/products/detailed
#            - RewritePath=/api/v1/products/(?<segment>.*), /api/v1/products/detailed/$\{segment}
#
#        - id: product-service-post-update-delete
#          uri: lb://product-service
#          predicates:
#            - Method=POST,UPDATE,DELETE
#            - Path=/api/v1/products/**

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/v1/categories/**, /api/v1/producers/**, /api/v1/products/**, /api/v1/pests/**, /api/v1/cultures/**, /api/v1/filters/**
        - id: catalog-service-swagger
          uri: lb://catalog-service
          predicates:
            - Path=/catalog-service/v3/api-docs
          filters:
            - StripPrefix=1

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
        - id: inventory-service-swagger
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/v3/api-docs
          filters:
            - StripPrefix=1

#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/api/v1/orders/**
#        - id: order-service-swagger
#          uri: lb://order-service
#          predicates:
#            - Path=/order-service/v3/api-docs
#          filters:
#            - StripPrefix=1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /inventory-service/v3/api-docs
        name: Inventory Service
      - url: /catalog-service/v3/api-docs
        name: Catalog Service
#      - url: /order-service/v3/api-docs
#        name: Order Service
