drop table if exists product cascade;
create table product
(
    id    bigint generated by default as identity,
    price float(53)    not null,
    name  varchar(300) not null unique,
    constraint product_pk primary key (id)
);
