create table category
(
    id   integer generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table subcategory
(
    id          integer generated by default as identity,
    name        varchar(255) not null,
    category_id integer      not null,
    primary key (id)
);

create table product_property
(
    id   integer generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table subcategory_properties
(
    subcategory_id integer not null,
    property_id    integer not null
);

create table product_property_value
(
    product_id  bigint      not null,
    property_id integer      not null,
    prop_value  varchar(255) not null,
    primary key (product_id, property_id)
);

alter table product
    add column subcategory_id integer not null default 1;

alter table category
    add constraint category_name_uk unique (name);

alter table subcategory
    add constraint sub_category_name_uk unique (name);

alter table product
    add constraint product_subcategory_id_fk
        foreign key (subcategory_id)
            references subcategory;

alter table subcategory
    add constraint subcategory_category_id_fk
        foreign key (category_id)
            references category;

alter table subcategory_properties
    add constraint subcat_props_subcat_id_fk
        foreign key (subcategory_id)
            references subcategory;

alter table subcategory_properties
    add constraint subcat_props_prop_id_fk
        foreign key (property_id)
            references product_property;