create table category
(
    id   integer generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table subcategory
(
    id          integer generated by default as identity,
    name        varchar(255) not null,
    category_id integer      not null,
    primary key (id)
);

create table product_property
(
    id   integer generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table subcategory_properties
(
    subcategory_id integer not null,
    property_id    integer not null
);

create table product_property_value
(
    product_id  bigint      not null,
    property_id integer      not null,
    prop_value  varchar(255) not null,
    primary key (product_id, property_id)
);

INSERT INTO category(name)
VALUES ('test1'),
       ('test2'),
       ('test3');

INSERT INTO subcategory(name, category_id)
VALUES ('test11', 1),
       ('test12', 1),
       ('test22', 2),
       ('test31', 3),
       ('test32', 3),
       ('test33', 3);


alter table if exists product
    add column subcategory_id integer not null default 1;

UPDATE product
SET subcategory_id = 1
WHERE id = 1;

UPDATE product
SET subcategory_id = 2
WHERE id = 2;

UPDATE product
SET subcategory_id = 3
WHERE id = 3;

alter table category
    add constraint category_name_uk unique (name);

alter table subcategory
    add constraint sub_category_name_uk unique (name);

alter table product
    add constraint product_subcategory_id_fk
        foreign key (subcategory_id)
            references subcategory;

alter table subcategory
    add constraint subcategory_category_id_fk
        foreign key (category_id)
            references category;

alter table subcategory_properties
    add constraint subcat_props_subcat_id_fk
        foreign key (subcategory_id)
            references subcategory;

alter table subcategory_properties
    add constraint subcat_props_prop_id_fk
        foreign key (property_id)
            references product_property;

INSERT INTO product_property(name)
VALUES ('height'),
       ('width'),
       ('color'),
       ('margin');

INSERT INTO subcategory_properties (subcategory_id, property_id)
VALUES (1, 1),
       (2, 2),
       (2, 3),
       (3, 4);

INSERT INTO product_property_value(product_id, property_id, prop_value)
VALUES (1, 1, '12px'),
       (2, 2, '30px'),
       (2, 3, 'red'),
       (3, 4, '10px');