create table users
(
    id       bigint generated by default as identity,
    login    varchar(20)  not null,
    password varchar(200) not null,
    name     varchar(30),
    surname  varchar(30),
    role     varchar(20)  not null check (name in ('USER', 'ADMIN')),
    primary key (id)
);

alter table users
    add constraint users_login_uk unique (login);
