server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: eureka-server
          uri: http://localhost:7777
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:7777
          predicates:
            - Path=/eureka/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/categories/**, /api/v1/products/**, /api/v1/producers/**

        - id: inventory
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**

        - id: orders
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka