server:
  port: 8084

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/agroswit
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
  webflux:
    problemdetails:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka