server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 500KB
      max-request-size: 500KB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka