server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka
  mvc:
    problemdetails:
      enabled: true

storage:
  upload-dir: ${UPLOAD_DIR:uploads}
