server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agroswit
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 500KB
      max-request-size: 500KB
  data:
    web:
      pageable:
        one-indexed-parameters: true
  mvc:
    problemdetails:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka

minio:
  bucket: images
  endpoint: http://localhost:9000
  access-key: minio_user
  secret-key: minio_pass